### PR TITLE
Update README.md, fix import error

### PR DESCRIPTION
**Pull request by jim-v**

### CODE REVIEW

**Review by rohbotics — APPROVED** [review]

**Comment by jim-v** [comment]
Still needs work, and testing on a blue robot.

**Comment by rohbotics** [comment]
@davecrawley Did you test this on a blue robot?

**Comment by jim-v** [comment]
This has been tested on a blue robot by @davecrawley and me.  @rohbotics, please can you take a look at it.

**Review by rohbotics — APPROVED** [review]
:+1: The loop looks a lot more sane now. I like the decay instead of the on-off hysteresis.

**Pull request merged**
